SUCCESS="SUCCESS"
FAILED="FAILED"
ACTIVE="ACTIVE"
INACTIVE="INACTIVE"
VALID="VALID"
INVALID="INVALID"
EXISTED="EXISTED"
NOT_EXISTED="NOT_EXISTED"
VERIFIED="VERIFIED"
NOT_VERIFIED="NOT_VERIFIED"
EQUAL="EQUAL"
NOT_EQUAL="NOT_EQUAL"
DATABASE_ROLE="DATABASE_ROLE"
OPEN_MODE="OPEN_MODE"

DAY=$(date +"%d")
MONTH=$(date +"%m")
YEAR=$(date +"%Y")

LOG_PATH="/home/oracle/shell_scripts/v2/logs/log_${DAY}_${MONTH}_${YEAR}.log"

# f_u_show_log